### ISSUE TITLE
Update the error views

### ISSUE THREAD

**Issue by jamesplease** [jmeas/gistbook#370]
- [x] Compute the remaining minutes until you can log in. Once there are 0 minutes left, it should refresh the page for you. (resolved by #371) 
- [x] If you're not logged in, there should be a log in button right in the view (resolved by #374)
- [x] Share the styles between the error views to be more DRY (resolved by #372)
